export const ACTION_TYPE = {
  FETCH_USER_PROFILE_ASYNC: 'FETCH_USER_PROFILE_ASYNC',
  FETCH_USER_PROFILE_LOADING: 'FETCH_USER_PROFILE_LOADING',
  FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILED: 'FETCH_USER_PROFILE_FAILED'
};